apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: aspera-hsts
  name: aspera-01-pvc
  namespace: aspera
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ibmc-file-gold
